# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0002_auto_20171114_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(null=True, verbose_name='date joined'),
        ),
    ]
