# Generated by Django 2.0 on 2017-12-27 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0002_createsuperuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={'permissions': (('view_all_classrooms', 'Can view all classrooms'),)},
        ),
    ]
