# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0003_auto_20171115_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.DateField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='attendance',
            field=models.ManyToManyField(to='ecweb.Attendance'),
        ),
    ]
