# Generated by Django 2.0 on 2017-12-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0004_auto_20171211_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
