# Generated by Django 2.0 on 2017-12-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0004_classroom_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
