# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0004_auto_20171118_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('title', models.CharField(max_length=30)),
                ('local', models.CharField(max_length=30)),
            ],
        ),
    ]
