# Generated by Django 2.0 on 2017-12-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0005_classroom_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={'permissions': (('view_all_classrooms', 'Can view all classrooms'), ('view_classroom_detail', 'Can view the classroom detail'))},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': (('view_classroom_detail', 'Can view the classroom detail'),)},
        ),
    ]
