# Generated by Django 2.0 on 2017-12-12 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0005_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='youtube',
        ),
        migrations.AddField(
            model_name='pdf_file',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecweb.ClassRoom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtube',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecweb.ClassRoom'),
            preserve_default=False,
        ),
    ]
