# Generated by Django 2.0 on 2017-12-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0006_auto_20171212_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
