# Generated by Django 2.0 on 2017-12-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0007_auto_20171213_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/user_default.png', upload_to='avatars/'),
        ),
    ]
