# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0007_menssage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='menssage',
            field=models.ManyToManyField(blank=True, to='ecweb.Menssage'),
        ),
    ]
