# Generated by Django 2.0 on 2017-12-17 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0008_auto_20171215_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lesson', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecweb.Class')),
            ],
        ),
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pdf_file',
            name='classroom',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='nivel',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='classroom',
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(to='ecweb.Student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(to='ecweb.Teacher'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/user_default.png', upload_to='avatars/profiles'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Pdf_file',
        ),
        migrations.AddField(
            model_name='testgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecweb.Student'),
        ),
        migrations.AddField(
            model_name='testgrade',
            name='test_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecweb.Test'),
        ),
        migrations.AddField(
            model_name='test',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecweb.ClassRoom'),
        ),
        migrations.AddField(
            model_name='classattendance',
            name='students',
            field=models.ManyToManyField(to='ecweb.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecweb.ClassRoom'),
        ),
        migrations.AddField(
            model_name='class',
            name='files',
            field=models.ManyToManyField(to='ecweb.PdfFile'),
        ),
        migrations.AddField(
            model_name='class',
            name='videos',
            field=models.ManyToManyField(to='ecweb.Youtube'),
        ),
    ]
