# Generated by Django 2.0 on 2017-12-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0008_classroom_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='number_class',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
