# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0008_auto_20171118_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
