# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 23:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0009_auto_20171118_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go', models.BooleanField(default=False)),
                ('dgo', models.BooleanField(default=False)),
                ('dknow', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
