# Generated by Django 2.0 on 2018-01-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0010_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_event',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_event',
            field=models.DateTimeField(),
        ),
    ]
