# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0010_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='confirm',
            field=models.ManyToManyField(blank=True, to='ecweb.Confirmed'),
        ),
    ]
