# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0011_calendar_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_test', models.DateField(blank=True, null=True)),
                ('grade', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
