# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0013_auto_20171120_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attendance',
            field=models.ManyToManyField(blank=True, to='ecweb.Attendance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grades',
            field=models.ManyToManyField(blank=True, to='ecweb.StudentTests'),
        ),
    ]
