# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0014_auto_20171120_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_of_course',
            field=models.CharField(blank=True, choices=[('1-month', '1-month'), ('6-month', '6-month')], max_length=30),
        ),
    ]
